package ru.wartemw.staff_register.build_service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Banking_organization service. Represents a row in the &quot;staff_register_Banking_organization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.wartemw.staff_register.build_service.model.impl.Banking_organizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.wartemw.staff_register.build_service.model.impl.Banking_organizationImpl}.
 * </p>
 *
 * @author wARTEMw
 * @see Banking_organization
 * @see ru.wartemw.staff_register.build_service.model.impl.Banking_organizationImpl
 * @see ru.wartemw.staff_register.build_service.model.impl.Banking_organizationModelImpl
 * @generated
 */
public interface Banking_organizationModel extends BaseModel<Banking_organization> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a banking_organization model instance should use the {@link Banking_organization} interface instead.
     */

    /**
     * Returns the primary key of this banking_organization.
     *
     * @return the primary key of this banking_organization
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this banking_organization.
     *
     * @param primaryKey the primary key of this banking_organization
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the banking_organization i d of this banking_organization.
     *
     * @return the banking_organization i d of this banking_organization
     */
    public long getBanking_organizationID();

    /**
     * Sets the banking_organization i d of this banking_organization.
     *
     * @param banking_organizationID the banking_organization i d of this banking_organization
     */
    public void setBanking_organizationID(long banking_organizationID);

    /**
     * Returns the name of this banking_organization.
     *
     * @return the name of this banking_organization
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this banking_organization.
     *
     * @param name the name of this banking_organization
     */
    public void setName(String name);

    /**
     * Returns the identification_code of this banking_organization.
     *
     * @return the identification_code of this banking_organization
     */
    public int getIdentification_code();

    /**
     * Sets the identification_code of this banking_organization.
     *
     * @param identification_code the identification_code of this banking_organization
     */
    public void setIdentification_code(int identification_code);

    /**
     * Returns the address of this banking_organization.
     *
     * @return the address of this banking_organization
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this banking_organization.
     *
     * @param address the address of this banking_organization
     */
    public void setAddress(String address);

    /**
     * Returns the worker i d of this banking_organization.
     *
     * @return the worker i d of this banking_organization
     */
    public long getWorkerID();

    /**
     * Sets the worker i d of this banking_organization.
     *
     * @param workerID the worker i d of this banking_organization
     */
    public void setWorkerID(long workerID);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        ru.wartemw.staff_register.build_service.model.Banking_organization banking_organization);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.wartemw.staff_register.build_service.model.Banking_organization> toCacheModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Banking_organization toEscapedModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Banking_organization toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
