package ru.wartemw.staff_register.build_service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Position_directory service. Represents a row in the &quot;staff_register_Position_directory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.wartemw.staff_register.build_service.model.impl.Position_directoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.wartemw.staff_register.build_service.model.impl.Position_directoryImpl}.
 * </p>
 *
 * @author wARTEMw
 * @see Position_directory
 * @see ru.wartemw.staff_register.build_service.model.impl.Position_directoryImpl
 * @see ru.wartemw.staff_register.build_service.model.impl.Position_directoryModelImpl
 * @generated
 */
public interface Position_directoryModel extends BaseModel<Position_directory> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a position_directory model instance should use the {@link Position_directory} interface instead.
     */

    /**
     * Returns the primary key of this position_directory.
     *
     * @return the primary key of this position_directory
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this position_directory.
     *
     * @param primaryKey the primary key of this position_directory
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the position_directory i d of this position_directory.
     *
     * @return the position_directory i d of this position_directory
     */
    public long getPosition_directoryID();

    /**
     * Sets the position_directory i d of this position_directory.
     *
     * @param position_directoryID the position_directory i d of this position_directory
     */
    public void setPosition_directoryID(long position_directoryID);

    /**
     * Returns the name of this position_directory.
     *
     * @return the name of this position_directory
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this position_directory.
     *
     * @param name the name of this position_directory
     */
    public void setName(String name);

    /**
     * Returns the archival_status of this position_directory.
     *
     * @return the archival_status of this position_directory
     */
    public boolean getArchival_status();

    /**
     * Returns <code>true</code> if this position_directory is archival_status.
     *
     * @return <code>true</code> if this position_directory is archival_status; <code>false</code> otherwise
     */
    public boolean isArchival_status();

    /**
     * Sets whether this position_directory is archival_status.
     *
     * @param archival_status the archival_status of this position_directory
     */
    public void setArchival_status(boolean archival_status);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        ru.wartemw.staff_register.build_service.model.Position_directory position_directory);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.wartemw.staff_register.build_service.model.Position_directory> toCacheModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Position_directory toEscapedModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Position_directory toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
