package ru.wartemw.staff_register.build_service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Worker service. Represents a row in the &quot;staff_register_Worker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.wartemw.staff_register.build_service.model.impl.WorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.wartemw.staff_register.build_service.model.impl.WorkerImpl}.
 * </p>
 *
 * @author wARTEMw
 * @see Worker
 * @see ru.wartemw.staff_register.build_service.model.impl.WorkerImpl
 * @see ru.wartemw.staff_register.build_service.model.impl.WorkerModelImpl
 * @generated
 */
public interface WorkerModel extends BaseModel<Worker> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a worker model instance should use the {@link Worker} interface instead.
     */

    /**
     * Returns the primary key of this worker.
     *
     * @return the primary key of this worker
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this worker.
     *
     * @param primaryKey the primary key of this worker
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the worker i d of this worker.
     *
     * @return the worker i d of this worker
     */
    public long getWorkerID();

    /**
     * Sets the worker i d of this worker.
     *
     * @param workerID the worker i d of this worker
     */
    public void setWorkerID(long workerID);

    /**
     * Returns the surname of this worker.
     *
     * @return the surname of this worker
     */
    @AutoEscape
    public String getSurname();

    /**
     * Sets the surname of this worker.
     *
     * @param surname the surname of this worker
     */
    public void setSurname(String surname);

    /**
     * Returns the name of this worker.
     *
     * @return the name of this worker
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this worker.
     *
     * @param name the name of this worker
     */
    public void setName(String name);

    /**
     * Returns the patronymic of this worker.
     *
     * @return the patronymic of this worker
     */
    @AutoEscape
    public String getPatronymic();

    /**
     * Sets the patronymic of this worker.
     *
     * @param patronymic the patronymic of this worker
     */
    public void setPatronymic(String patronymic);

    /**
     * Returns the gender of this worker.
     *
     * @return the gender of this worker
     */
    @AutoEscape
    public String getGender();

    /**
     * Sets the gender of this worker.
     *
     * @param gender the gender of this worker
     */
    public void setGender(String gender);

    /**
     * Returns the date_of_birth of this worker.
     *
     * @return the date_of_birth of this worker
     */
    public Date getDate_of_birth();

    /**
     * Sets the date_of_birth of this worker.
     *
     * @param date_of_birth the date_of_birth of this worker
     */
    public void setDate_of_birth(Date date_of_birth);

    /**
     * Returns the date_of_employment of this worker.
     *
     * @return the date_of_employment of this worker
     */
    public Date getDate_of_employment();

    /**
     * Sets the date_of_employment of this worker.
     *
     * @param date_of_employment the date_of_employment of this worker
     */
    public void setDate_of_employment(Date date_of_employment);

    /**
     * Returns the salary_level of this worker.
     *
     * @return the salary_level of this worker
     */
    public long getSalary_level();

    /**
     * Sets the salary_level of this worker.
     *
     * @param salary_level the salary_level of this worker
     */
    public void setSalary_level(long salary_level);

    /**
     * Returns the work_number of this worker.
     *
     * @return the work_number of this worker
     */
    public long getWork_number();

    /**
     * Sets the work_number of this worker.
     *
     * @param work_number the work_number of this worker
     */
    public void setWork_number(long work_number);

    /**
     * Returns the telephone_number of this worker.
     *
     * @return the telephone_number of this worker
     */
    public long getTelephone_number();

    /**
     * Sets the telephone_number of this worker.
     *
     * @param telephone_number the telephone_number of this worker
     */
    public void setTelephone_number(long telephone_number);

    /**
     * Returns the archival_status of this worker.
     *
     * @return the archival_status of this worker
     */
    public boolean getArchival_status();

    /**
     * Returns <code>true</code> if this worker is archival_status.
     *
     * @return <code>true</code> if this worker is archival_status; <code>false</code> otherwise
     */
    public boolean isArchival_status();

    /**
     * Sets whether this worker is archival_status.
     *
     * @param archival_status the archival_status of this worker
     */
    public void setArchival_status(boolean archival_status);

    /**
     * Returns the position_directory i d of this worker.
     *
     * @return the position_directory i d of this worker
     */
    public long getPosition_directoryID();

    /**
     * Sets the position_directory i d of this worker.
     *
     * @param position_directoryID the position_directory i d of this worker
     */
    public void setPosition_directoryID(long position_directoryID);

    /**
     * Returns the banking_organization i d of this worker.
     *
     * @return the banking_organization i d of this worker
     */
    public long getBanking_organizationID();

    /**
     * Sets the banking_organization i d of this worker.
     *
     * @param banking_organizationID the banking_organization i d of this worker
     */
    public void setBanking_organizationID(long banking_organizationID);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        ru.wartemw.staff_register.build_service.model.Worker worker);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.wartemw.staff_register.build_service.model.Worker> toCacheModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Worker toEscapedModel();

    @Override
    public ru.wartemw.staff_register.build_service.model.Worker toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
