package ru.wartemw.staff_register.build_service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.wartemw.staff_register.build_service.model.Position_directory;
import ru.wartemw.staff_register.build_service.service.Position_directoryLocalServiceUtil;

/**
 * The extended model base implementation for the Position_directory service. Represents a row in the &quot;staff_register_Position_directory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Position_directoryImpl}.
 * </p>
 *
 * @author wARTEMw
 * @see Position_directoryImpl
 * @see ru.wartemw.staff_register.build_service.model.Position_directory
 * @generated
 */
public abstract class Position_directoryBaseImpl
    extends Position_directoryModelImpl implements Position_directory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a position_directory model instance should use the {@link Position_directory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Position_directoryLocalServiceUtil.addPosition_directory(this);
        } else {
            Position_directoryLocalServiceUtil.updatePosition_directory(this);
        }
    }
}
