package ru.wartemw.staff_register.build_service.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import ru.wartemw.staff_register.build_service.model.Position_directory;
import ru.wartemw.staff_register.build_service.service.Position_directoryLocalService;
import ru.wartemw.staff_register.build_service.service.persistence.Banking_organizationPersistence;
import ru.wartemw.staff_register.build_service.service.persistence.Position_directoryPersistence;
import ru.wartemw.staff_register.build_service.service.persistence.WorkerPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the position_directory local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ru.wartemw.staff_register.build_service.service.impl.Position_directoryLocalServiceImpl}.
 * </p>
 *
 * @author wARTEMw
 * @see ru.wartemw.staff_register.build_service.service.impl.Position_directoryLocalServiceImpl
 * @see ru.wartemw.staff_register.build_service.service.Position_directoryLocalServiceUtil
 * @generated
 */
public abstract class Position_directoryLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements Position_directoryLocalService,
        IdentifiableBean {
    @BeanReference(type = ru.wartemw.staff_register.build_service.service.Banking_organizationLocalService.class)
    protected ru.wartemw.staff_register.build_service.service.Banking_organizationLocalService banking_organizationLocalService;
    @BeanReference(type = Banking_organizationPersistence.class)
    protected Banking_organizationPersistence banking_organizationPersistence;
    @BeanReference(type = ru.wartemw.staff_register.build_service.service.Position_directoryLocalService.class)
    protected ru.wartemw.staff_register.build_service.service.Position_directoryLocalService position_directoryLocalService;
    @BeanReference(type = Position_directoryPersistence.class)
    protected Position_directoryPersistence position_directoryPersistence;
    @BeanReference(type = ru.wartemw.staff_register.build_service.service.WorkerLocalService.class)
    protected ru.wartemw.staff_register.build_service.service.WorkerLocalService workerLocalService;
    @BeanReference(type = WorkerPersistence.class)
    protected WorkerPersistence workerPersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private Position_directoryLocalServiceClpInvoker _clpInvoker = new Position_directoryLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link ru.wartemw.staff_register.build_service.service.Position_directoryLocalServiceUtil} to access the position_directory local service.
     */

    /**
     * Adds the position_directory to the database. Also notifies the appropriate model listeners.
     *
     * @param position_directory the position_directory
     * @return the position_directory that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Position_directory addPosition_directory(
        Position_directory position_directory) throws SystemException {
        position_directory.setNew(true);

        return position_directoryPersistence.update(position_directory);
    }

    /**
     * Creates a new position_directory with the primary key. Does not add the position_directory to the database.
     *
     * @param position_directoryID the primary key for the new position_directory
     * @return the new position_directory
     */
    @Override
    public Position_directory createPosition_directory(
        long position_directoryID) {
        return position_directoryPersistence.create(position_directoryID);
    }

    /**
     * Deletes the position_directory with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param position_directoryID the primary key of the position_directory
     * @return the position_directory that was removed
     * @throws PortalException if a position_directory with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Position_directory deletePosition_directory(
        long position_directoryID) throws PortalException, SystemException {
        return position_directoryPersistence.remove(position_directoryID);
    }

    /**
     * Deletes the position_directory from the database. Also notifies the appropriate model listeners.
     *
     * @param position_directory the position_directory
     * @return the position_directory that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public Position_directory deletePosition_directory(
        Position_directory position_directory) throws SystemException {
        return position_directoryPersistence.remove(position_directory);
    }

    @Override
    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(Position_directory.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return position_directoryPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ru.wartemw.staff_register.build_service.model.impl.Position_directoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return position_directoryPersistence.findWithDynamicQuery(dynamicQuery,
            start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ru.wartemw.staff_register.build_service.model.impl.Position_directoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return position_directoryPersistence.findWithDynamicQuery(dynamicQuery,
            start, end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return position_directoryPersistence.countWithDynamicQuery(dynamicQuery);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @param projection the projection to apply to the query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery,
        Projection projection) throws SystemException {
        return position_directoryPersistence.countWithDynamicQuery(dynamicQuery,
            projection);
    }

    @Override
    public Position_directory fetchPosition_directory(long position_directoryID)
        throws SystemException {
        return position_directoryPersistence.fetchByPrimaryKey(position_directoryID);
    }

    /**
     * Returns the position_directory with the primary key.
     *
     * @param position_directoryID the primary key of the position_directory
     * @return the position_directory
     * @throws PortalException if a position_directory with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public Position_directory getPosition_directory(long position_directoryID)
        throws PortalException, SystemException {
        return position_directoryPersistence.findByPrimaryKey(position_directoryID);
    }

    @Override
    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return position_directoryPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the position_directories.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ru.wartemw.staff_register.build_service.model.impl.Position_directoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param start the lower bound of the range of position_directories
     * @param end the upper bound of the range of position_directories (not inclusive)
     * @return the range of position_directories
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<Position_directory> getPosition_directories(int start, int end)
        throws SystemException {
        return position_directoryPersistence.findAll(start, end);
    }

    /**
     * Returns the number of position_directories.
     *
     * @return the number of position_directories
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getPosition_directoriesCount() throws SystemException {
        return position_directoryPersistence.countAll();
    }

    /**
     * Updates the position_directory in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param position_directory the position_directory
     * @return the position_directory that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public Position_directory updatePosition_directory(
        Position_directory position_directory) throws SystemException {
        return position_directoryPersistence.update(position_directory);
    }

    /**
     * Returns the banking_organization local service.
     *
     * @return the banking_organization local service
     */
    public ru.wartemw.staff_register.build_service.service.Banking_organizationLocalService getBanking_organizationLocalService() {
        return banking_organizationLocalService;
    }

    /**
     * Sets the banking_organization local service.
     *
     * @param banking_organizationLocalService the banking_organization local service
     */
    public void setBanking_organizationLocalService(
        ru.wartemw.staff_register.build_service.service.Banking_organizationLocalService banking_organizationLocalService) {
        this.banking_organizationLocalService = banking_organizationLocalService;
    }

    /**
     * Returns the banking_organization persistence.
     *
     * @return the banking_organization persistence
     */
    public Banking_organizationPersistence getBanking_organizationPersistence() {
        return banking_organizationPersistence;
    }

    /**
     * Sets the banking_organization persistence.
     *
     * @param banking_organizationPersistence the banking_organization persistence
     */
    public void setBanking_organizationPersistence(
        Banking_organizationPersistence banking_organizationPersistence) {
        this.banking_organizationPersistence = banking_organizationPersistence;
    }

    /**
     * Returns the position_directory local service.
     *
     * @return the position_directory local service
     */
    public ru.wartemw.staff_register.build_service.service.Position_directoryLocalService getPosition_directoryLocalService() {
        return position_directoryLocalService;
    }

    /**
     * Sets the position_directory local service.
     *
     * @param position_directoryLocalService the position_directory local service
     */
    public void setPosition_directoryLocalService(
        ru.wartemw.staff_register.build_service.service.Position_directoryLocalService position_directoryLocalService) {
        this.position_directoryLocalService = position_directoryLocalService;
    }

    /**
     * Returns the position_directory persistence.
     *
     * @return the position_directory persistence
     */
    public Position_directoryPersistence getPosition_directoryPersistence() {
        return position_directoryPersistence;
    }

    /**
     * Sets the position_directory persistence.
     *
     * @param position_directoryPersistence the position_directory persistence
     */
    public void setPosition_directoryPersistence(
        Position_directoryPersistence position_directoryPersistence) {
        this.position_directoryPersistence = position_directoryPersistence;
    }

    /**
     * Returns the worker local service.
     *
     * @return the worker local service
     */
    public ru.wartemw.staff_register.build_service.service.WorkerLocalService getWorkerLocalService() {
        return workerLocalService;
    }

    /**
     * Sets the worker local service.
     *
     * @param workerLocalService the worker local service
     */
    public void setWorkerLocalService(
        ru.wartemw.staff_register.build_service.service.WorkerLocalService workerLocalService) {
        this.workerLocalService = workerLocalService;
    }

    /**
     * Returns the worker persistence.
     *
     * @return the worker persistence
     */
    public WorkerPersistence getWorkerPersistence() {
        return workerPersistence;
    }

    /**
     * Sets the worker persistence.
     *
     * @param workerPersistence the worker persistence
     */
    public void setWorkerPersistence(WorkerPersistence workerPersistence) {
        this.workerPersistence = workerPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("ru.wartemw.staff_register.build_service.model.Position_directory",
            position_directoryLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "ru.wartemw.staff_register.build_service.model.Position_directory");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Position_directory.class;
    }

    protected String getModelClassName() {
        return Position_directory.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = position_directoryPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
